version: 2

sources:
  - name: staging
    schema: STAGING
    tables:
      - name: RAW_PATIENTS
      - name: RAW_ENCOUNTERS
      - name: RAW_PROVIDERS
      - name: RAW_ORGANIZATIONS
      - name: RAW_PAYORS
      - name: RAW_CONDITIONS
      - name: RAW_MEDICATIONS
      - name: RAW_PROCEDURES
      - name: RAW_CLAIMS
