version: 2

models:
  - name: dim_patients
    description: "Silver 3NF Dimension table for Patients"
    columns:
      - name: patient_id
        tests:
          - unique
          - not_null

  - name: dim_providers
    description: "Silver 3NF Dimension table for Physicians"
    columns:
      - name: provider_id
        tests:
          - unique
          - not_null

  - name: dim_organizations
    description: "Silver 3NF Dimension table for Hospital Organizations"
    columns:
      - name: organization_id
        tests:
          - unique
          - not_null

  - name: dim_payors
    description: "Silver 3NF Dimension table for Insurance Payors"
    columns:
      - name: payor_id
        tests:
          - unique
          - not_null

  - name: fct_encounters
    description: "Silver Fact table for Patient Encounters (Incremental)"
    columns:
      - name: encounter_id
        tests:
          - unique
          - not_null
      - name: patient_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_patients')
              field: patient_id
      - name: provider_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_providers')
              field: provider_id
      - name: organization_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_organizations')
              field: organization_id

  - name: fct_claims
    description: "Silver Fact table for Medical Claims"
    columns:
      - name: claim_id
        tests:
          - unique
          - not_null
      - name: patient_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_patients')
              field: patient_id

  - name: gold_fct_patient_encounters
    description: "Gold Star Schema Fact Table"
    columns:
      - name: encounter_id
        tests:
          - unique
          - not_null
      - name: patient_id
        tests:
          - not_null
      - name: provider_id
        tests:
          - not_null
